package com.sdtechnocrat.ahoy.data

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize

@Parcelize
data class PlanItem(

	@field:SerializedName("is_private")
	val isPrivate: String? = null,

	@field:SerializedName("trial_recurrence")
	val trialRecurrence: String? = null,

	@field:SerializedName("monthly_fee")
	val monthlyFee: String? = null,

	@field:SerializedName("language_id")
	val languageId: String? = null,

	@field:SerializedName("is_post_paid")
	val isPostPaid: String? = null,

	@field:SerializedName("frequency")
	val frequency: String? = null,

	@field:SerializedName("duration")
	val duration: String? = null,

	@field:SerializedName("last_updated_by")
	val lastUpdatedBy: String? = null,

	@field:SerializedName("price")
	val price: String? = null,

	@field:SerializedName("currency")
	val currency: Currency? = null,

	@field:SerializedName("id")
	val id: String? = null,

	@field:SerializedName("last_updated_date")
	val lastUpdatedDate: String? = null,

	@field:SerializedName("auto_generated_content_ids")
	val autoGeneratedContentIds: String? = null,

	@field:SerializedName("unique_id")
	val uniqueId: String? = null,

	@field:SerializedName("ip")
	val ip: String? = null,

	@field:SerializedName("auto_generated_content")
	val autoGeneratedContent: String? = null,

	@field:SerializedName("id_sequency")
	val idSequency: String? = null,

	@field:SerializedName("startup_discount")
	val startupDiscount: String? = null,

	@field:SerializedName("rules_id")
	val rulesId: String? = null,

	@field:SerializedName("is_default")
	val isDefault: String? = null,

	@field:SerializedName("created_by")
	val createdBy: String? = null,

	@field:SerializedName("monetized_user_type")
	val monetizedUserType: String? = null,

	@field:SerializedName("recurrence")
	val recurrence: String? = null,

	@field:SerializedName("parent_id")
	val parentId: String? = null,

	@field:SerializedName("name")
	val name: String? = null,

	@field:SerializedName("is_auto_generated")
	val isAutoGenerated: String? = null,

	@field:SerializedName("short_desc")
	val shortDesc: String? = null,

	@field:SerializedName("studio_id")
	val studioId: String? = null,

	@field:SerializedName("created_date")
	val createdDate: String? = null,

	@field:SerializedName("is_sub_account")
	val isSubAccount: String? = null,

	@field:SerializedName("trial_period")
	val trialPeriod: String? = null,

	@field:SerializedName("is_subscription_bundle")
	val isSubscriptionBundle: String? = null,

	@field:SerializedName("status")
	val status: String? = null
) : Parcelable

@Parcelize
data class Currency(

	@field:SerializedName("country_code")
	val countryCode: String? = null,

	@field:SerializedName("symbol")
	val symbol: String? = null,

	@field:SerializedName("code")
	val code: String? = null,

	@field:SerializedName("iso_num")
	val isoNum: String? = null,

	@field:SerializedName("id")
	val id: String? = null,

	@field:SerializedName("title")
	val title: String? = null,

	@field:SerializedName("is_zero_decimal")
	val isZeroDecimal: String? = null
) : Parcelable
